=== mmmajder/XML-project/Schema/P_Sema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/patent" xmlns:pat="http://www.ftn.uns.ac.rs/patent">

    <xs:element name="Zahtev_za_priznanje_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pat:Osnovne_informacije_o_zahtevu_za_priznanje_patenta"/>
                <xs:element ref="pat:Sadrzaj_zahteva_za_priznanje_patenta"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Osnovne_informacije_o_zahtevu_za_priznanje_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Broj_prijave" type="pat:TBroj_prijave" default="P-13245/2019"/>
                <xs:element name="Datum_prijema" type="xs:date"/>
                <xs:element name="Priznati_datum_podnosenja" type="xs:date"/>
                <xs:element minOccurs="0" name="Stanje">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="NA_CEKANJU"/>
                            <xs:enumeration value="USPESNO"/>
                            <xs:enumeration value="NEUSPESNO"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Sadrzaj_zahteva_za_priznanje_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naziv_pronalaska" maxOccurs="2" minOccurs="2">
                    <xs:complexType mixed="false">
                        <xs:attribute name="Jezik" type="pat:TJezik"/>
                        <xs:attribute name="Naziv" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_podnosiocu_prijave">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Podnosilac_prijave_je_i_pronalazac" type="xs:boolean"/>
                            <xs:element name="Podnosilac_prijave" type="pat:TLice"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_pronalazacu" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Pronalazac_ne_zeli_da_bude_naveden" type="xs:boolean"/>
                            <xs:element minOccurs="0" name="Pronalazac" type="pat:TFizicko_Lice"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_punomocniku">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Vrsta_punomocnika">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="PUNOMOCNIK_ZA_ZASTUPANJE"/>
                                        <xs:enumeration value="PUNOMOCNIK_ZA_PRIJEM_PISMENA"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Zajednicki_predstavnik" type="xs:boolean"/>
                            <xs:element name="Punomocnik" type="pat:TLice"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Dostavljanje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Adresa_za_dostavljanje" type="pat:Adresa"
                                minOccurs="0"/>
                            <xs:element name="Nacin_dostave">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ELEKTRONSKIM_PUTEM"/>
                                        <xs:enumeration value="PAPIRNA_FORM"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_prijavi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Vrsta_prijave">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="DOPUNSKA"/>
                                        <xs:enumeration value="IZDVOJENA"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_osnovne_prijave" type="pat:TBroj_prijave"/>
                            <xs:element name="Datum_podnosenja_prijave" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava" maxOccurs="1"
                    minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="Ranija_prijava">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Broj_ranije_prijave"
                                            type="pat:TBroj_prijave"/>
                                        <xs:element name="Datum_podnosenja_priave" type="xs:date"/>
                                        <xs:element name="Dvoslovna_oznaka" default="NS">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern value="[A-Za-z]{2}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TBroj_prijave">
        <xs:restriction base="xs:string">
            <xs:pattern value="P-[0-9]*/[0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TLice" abstract="true">
        <xs:sequence>
            <xs:element name="Adresa_lica" type="pat:Adresa"/>
            <xs:element default="+381 640381181" name="Broj_telefona" type="pat:TBroj_telefona"/>
            <xs:element name="Broj_faksa" type="xs:string"/>
            <xs:element name="E_posta" default="ajder.milan2000@gmail.com" type="pat:TE_posta"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_Lice">
        <xs:complexContent>
            <xs:extension base="pat:TLice">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime" type="xs:string"/>
                    <xs:element name="Drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravno_Lice">
        <xs:complexContent>
            <xs:extension base="pat:TLice">
                <xs:sequence>
                    <xs:element name="Poslovno_ime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="TBroj_telefona">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+\d{3} \d{8,9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Adresa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj_u_ulici" type="xs:positiveInteger"/>
            <xs:element name="Postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="11000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Mesto" type="xs:string"/>
            <xs:element name="Drzava" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TE_posta">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TJezik">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SRPSKI"/>
            <xs:enumeration value="ENGLESKI"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mmmajder/XML-project/Examples/Primer_P.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_patenta xmlns="http://www.ftn.uns.ac.rs/patent"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/patent file:/C:/Users/Korisnik/Desktop/FAKS/XML/Projekat/P_Sema.xsd">
    <Osnovne_informacije_o_zahtevu_za_priznanje_patenta>
        <Broj_prijave></Broj_prijave>
        <Datum_prijema>2020-01-01</Datum_prijema>
        <Priznati_datum_podnosenja>2020-01-01</Priznati_datum_podnosenja>
    </Osnovne_informacije_o_zahtevu_za_priznanje_patenta>
    <Sadrzaj_zahteva_za_priznanje_patenta>
        <Naziv_pronalaska/>
        <Naziv_pronalaska/>
        <Podaci_o_podnosiocu_prijave>
            <Podnosilac_prijave_je_i_pronalazac>true</Podnosilac_prijave_je_i_pronalazac>
            <Podnosilac_prijave>
                <Osnovni_podaci_o_licu>
                    <Adresa_lica>
                        <Ulica></Ulica>
                        <Broj_u_ulici>3</Broj_u_ulici>
                        <Postanski_broj>21000</Postanski_broj>
                        <Mesto></Mesto>
                        <Drzava></Drzava>
                    </Adresa_lica>
                    <Broj_telefona></Broj_telefona>
                    <Broj_faksa></Broj_faksa>
                    <E_posta></E_posta>
                </Osnovni_podaci_o_licu>
            </Podnosilac_prijave>
        </Podaci_o_podnosiocu_prijave>
        <Podaci_o_pronalazacu>
            <Pronalazac>
                <Osnovni_podaci_o_licu>
                    <Adresa_lica>
                        <Ulica></Ulica>
                        <Broj_u_ulici>5</Broj_u_ulici>
                        <Postanski_broj>11000</Postanski_broj>
                        <Mesto></Mesto>
                        <Drzava></Drzava>
                    </Adresa_lica>
                    <Broj_telefona></Broj_telefona>
                    <Broj_faksa></Broj_faksa>
                    <E_posta></E_posta>
                </Osnovni_podaci_o_licu>
                <Ime></Ime>
                <Prezime></Prezime>
                <Drzavljanstvo></Drzavljanstvo>
            </Pronalazac>
            <Osnovni_podaci_o_licu>
                <Adresa_lica>
                    <Ulica></Ulica>
                    <Broj_u_ulici>7</Broj_u_ulici>
                    <Postanski_broj>21000</Postanski_broj>
                    <Mesto></Mesto>
                    <Drzava></Drzava>
                </Adresa_lica>
                <Broj_telefona></Broj_telefona>
                <Broj_faksa></Broj_faksa>
                <E_posta></E_posta>
            </Osnovni_podaci_o_licu>
        </Podaci_o_pronalazacu>
        <Podaci_o_punomocniku>
            <Vrsta_punomocnika>PUNOMOCNIK_ZA_ZASTUPANJE</Vrsta_punomocnika>
            <Zajednicki_predstavnik>false</Zajednicki_predstavnik>
            <Punomocnik>
                <Osnovni_podaci_o_licu>
                    <Adresa_lica>
                        <Ulica></Ulica>
                        <Broj_u_ulici>1</Broj_u_ulici>
                        <Postanski_broj>21000</Postanski_broj>
                        <Mesto></Mesto>
                        <Drzava></Drzava>
                    </Adresa_lica>
                    <Broj_telefona></Broj_telefona>
                    <Broj_faksa></Broj_faksa>
                    <E_posta></E_posta>
                </Osnovni_podaci_o_licu>
            </Punomocnik>
        </Podaci_o_punomocniku>
        <Dostavljanje>
            <Adresa_za_dostavljanje>
                <Ulica></Ulica>
                <Broj_u_ulici>1</Broj_u_ulici>
                <Postanski_broj>21000</Postanski_broj>
                <Mesto></Mesto>
                <Drzava></Drzava>
            </Adresa_za_dostavljanje>
            <Nacin_dostave>ELEKTRONSKIM_PUTEM</Nacin_dostave>
        </Dostavljanje>
        <Podaci_o_prijavi>
            <Vrsta_prijave>IZDVOJENA</Vrsta_prijave>
            <Broj_osnovne_prijave></Broj_osnovne_prijave>
            <Datum_podnosenja_prijave>2020-01-01</Datum_podnosenja_prijave>
        </Podaci_o_prijavi>
        <Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava></Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava>
    </Sadrzaj_zahteva_za_priznanje_patenta>
</Zahtev_za_priznanje_patenta>

=== mmmajder/XML-project/Parsers/data/P3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_patenta xmlns="http://www.ftn.uns.ac.rs/patent"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/patent file:/C:/Users/Korisnik/Desktop/FAKS/XML/Projekat/XML-project/Schema/P_Sema.xsd">
    <Osnovne_informacije_o_zahtevu_za_priznanje_patenta>
        <Broj_prijave>P123</Broj_prijave>
        <Datum_prijema>2020-01-01</Datum_prijema>
        <Priznati_datum_podnosenja>2020-01-01</Priznati_datum_podnosenja>
    </Osnovne_informacije_o_zahtevu_za_priznanje_patenta>
    <Sadrzaj_zahteva_za_priznanje_patenta>
        <Naziv_pronalaska Jezik="SRPSKI">Jako dobar patent</Naziv_pronalaska>
        <Naziv_pronalaska Jezik="ENGLESKI">Very good patent</Naziv_pronalaska>
        <Podaci_o_podnosiocu_prijave>
            <Podnosilac_prijave_je_i_pronalazac>false</Podnosilac_prijave_je_i_pronalazac>
            <Podnosilac_prijave xsi:type="TFizicko_Lice">
                <Osnovni_podaci_o_licu>
                    <Adresa_lica>
                        <Ulica>Bulevar</Ulica>
                        <Broj_u_ulici>21</Broj_u_ulici>
                        <Postanski_broj>22112</Postanski_broj>
                        <Mesto>Novi Sad</Mesto>
                        <Drzava>Srbija</Drzava>
                    </Adresa_lica>
                    <Broj_telefona>+381 644564651</Broj_telefona>
                    <Broj_faksa>156465</Broj_faksa>
                    <E_posta>mail@gmail.com</E_posta>
                </Osnovni_podaci_o_licu>
                <Ime>Joca</Ime>
                <Prezime>Jocic</Prezime>
                <Drzavljanstvo>Srpsko</Drzavljanstvo>
            </Podnosilac_prijave>
        </Podaci_o_podnosiocu_prijave>
        <Podaci_o_pronalazacu>
            <Osnovni_podaci_o_licu>
                <Adresa_lica>
                    <Ulica>Kisacka</Ulica>
                    <Broj_u_ulici>23</Broj_u_ulici>
                    <Postanski_broj>32312</Postanski_broj>
                    <Mesto>Novi Sad</Mesto>
                    <Drzava>Srbija</Drzava>
                </Adresa_lica>
                <Broj_telefona>+381 13243564</Broj_telefona>
                <Broj_faksa>468489</Broj_faksa>
                <E_posta>mail3@gmail.com</E_posta>
            </Osnovni_podaci_o_licu>
            <Ime>Pera</Ime>
            <Prezime>Perica</Prezime>
            <Drzavljanstvo>Srbija</Drzavljanstvo>
        </Podaci_o_pronalazacu>
        <Podaci_o_punomocniku>
            <Vrsta_punomocnika>PUNOMOCNIK_ZA_ZASTUPANJE</Vrsta_punomocnika>
            <Zajednicki_predstavnik>false</Zajednicki_predstavnik>
            <Punomocnik xsi:type="TPravno_lice">
                <Osnovni_podaci_o_licu>
                    <Adresa_lica>
                        <Ulica>Branislava Nusica</Ulica>
                        <Broj_u_ulici>43</Broj_u_ulici>
                        <Postanski_broj>21312</Postanski_broj>
                        <Mesto>Novi Sad</Mesto>
                        <Drzava>Srbija</Drzava>
                    </Adresa_lica>
                    <Broj_telefona>+381 45621348</Broj_telefona>
                    <Broj_faksa>321321</Broj_faksa>
                    <E_posta>mail4@gmail.com</E_posta>
                </Osnovni_podaci_o_licu>
                <Poslovno_ime>Joca komerc</Poslovno_ime>
            </Punomocnik>
        </Podaci_o_punomocniku>
        <Dostavljanje>
        	<!-- NIJE OBAVEZNA ADRESA OVDE -->
            <Nacin_dostave>ELEKTRONSKIM_PUTEM</Nacin_dostave>
        </Dostavljanje>
        <Podaci_o_prijavi>
            <Vrsta_prijave>DOPUNSKA</Vrsta_prijave>
            <Broj_osnovne_prijave>P1321</Broj_osnovne_prijave>
            <Datum_podnosenja_prijave>2022-02-02</Datum_podnosenja_prijave>
        </Podaci_o_prijavi>
        <Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava>
        	<Ranija_prijava>
                <Datum_podnosenja_priave>2022-02-02</Datum_podnosenja_priave>
                <Broj_ranije_prijave>P4323</Broj_ranije_prijave>
                <Dvoslovna_oznaka>RS</Dvoslovna_oznaka>
            </Ranija_prijava>
        </Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava>
    </Sadrzaj_zahteva_za_priznanje_patenta>
</Zahtev_za_priznanje_patenta>

=== mmmajder/XML-project/Parsers/data/Patent-primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_priznanje_patenta xmlns="http://www.ftn.uns.ac.rs/patent"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/patent file:/C:/Users/Korisnik/Desktop/FAKS/XML/Projekat/XML-project/Schema/P_Sema.xsd">
    <Osnovne_informacije_o_zahtevu_za_priznanje_patenta>
        <Broj_prijave>P-551/2019</Broj_prijave>
        <Datum_prijema>2022-02-05</Datum_prijema>
        <Priznati_datum_podnosenja>2022-02-05</Priznati_datum_podnosenja>
    </Osnovne_informacije_o_zahtevu_za_priznanje_patenta>
    <Sadrzaj_zahteva_za_priznanje_patenta>
        <Naziv_pronalaska Jezik="SRPSKI" Naziv="Leteci auto"/>
        <Naziv_pronalaska Jezik="ENGLESKI" Naziv="Flying car"/>
        <Podaci_o_podnosiocu_prijave>
            <Podnosilac_prijave_je_i_pronalazac>false</Podnosilac_prijave_je_i_pronalazac>
            <Podnosilac_prijave xsi:type="TFizicko_Lice">
                <Adresa_lica>
                    <Ulica>Bulevar oslobodjenja</Ulica>
                    <Broj_u_ulici>21</Broj_u_ulici>
                    <Postanski_broj>21123</Postanski_broj>
                    <Mesto>Novi Sad</Mesto>
                    <Drzava>Srbija</Drzava>
                </Adresa_lica>
                <Broj_telefona>+381 644564651</Broj_telefona>
                <Broj_faksa>156465</Broj_faksa>
                <E_posta>mail@gmail.com</E_posta>
                <Ime>Joca</Ime>
                <Prezime>Jocic</Prezime>
                <Drzavljanstvo>Srpsko</Drzavljanstvo>
            </Podnosilac_prijave>
        </Podaci_o_podnosiocu_prijave>
        <Podaci_o_pronalazacu>
            <Pronalazac_ne_zeli_da_bude_naveden>false</Pronalazac_ne_zeli_da_bude_naveden>
            <Pronalazac>
                <Adresa_lica>
                    <Ulica>Cirpanova</Ulica>
                    <Broj_u_ulici>32</Broj_u_ulici>
                    <Postanski_broj>32112</Postanski_broj>
                    <Mesto>Novi Sad</Mesto>
                    <Drzava>Srbija</Drzava>
                </Adresa_lica>
                <Broj_telefona>+381 45646456</Broj_telefona>
                <Broj_faksa>155416</Broj_faksa>
                <E_posta>mail2@gmail.com</E_posta>
                <Ime>Pera</Ime>
                <Prezime>Perica</Prezime>
                <Drzavljanstvo>Srbija</Drzavljanstvo>
            </Pronalazac>
        </Podaci_o_pronalazacu>
        <Podaci_o_punomocniku>
            <Vrsta_punomocnika>PUNOMOCNIK_ZA_ZASTUPANJE</Vrsta_punomocnika>
            <Zajednicki_predstavnik>false</Zajednicki_predstavnik>
            <Punomocnik xsi:type="TPravno_Lice">
                <Adresa_lica>
                    <Ulica>Branislava Nusica</Ulica>
                    <Broj_u_ulici>43</Broj_u_ulici>
                    <Postanski_broj>21312</Postanski_broj>
                    <Mesto>Novi Sad</Mesto>
                    <Drzava>Srbija</Drzava>
                </Adresa_lica>
                <Broj_telefona>+381 45621348</Broj_telefona>
                <Broj_faksa>321321</Broj_faksa>
                <E_posta>mail4@gmail.com</E_posta>
                <Poslovno_ime>Joca komerc</Poslovno_ime>
            </Punomocnik>
        </Podaci_o_punomocniku>
        <Dostavljanje>
            <Adresa_za_dostavljanje>
                <Ulica>Pavla Papa</Ulica>
                <Broj_u_ulici>12</Broj_u_ulici>
                <Postanski_broj>21890</Postanski_broj>
                <Mesto>Novi Sad</Mesto>
                <Drzava>Srbija</Drzava>
            </Adresa_za_dostavljanje>
            <Nacin_dostave>ELEKTRONSKIM_PUTEM</Nacin_dostave>
        </Dostavljanje>
        <Podaci_o_prijavi>
            <Vrsta_prijave>DOPUNSKA</Vrsta_prijave>
            <Broj_osnovne_prijave>P-1321/2021</Broj_osnovne_prijave>
            <Datum_podnosenja_prijave>2022-02-02</Datum_podnosenja_prijave>
        </Podaci_o_prijavi>
        <Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava>
            <Ranija_prijava>
	            <Broj_ranije_prijave>P-121/2011</Broj_ranije_prijave>
                <Datum_podnosenja_priave>2011-01-01</Datum_podnosenja_priave>
                <Dvoslovna_oznaka>RS</Dvoslovna_oznaka>
            </Ranija_prijava>
        </Zahtev_za_priznanje_prvenstva_iz_ranijih_prijava>
    </Sadrzaj_zahteva_za_priznanje_patenta>
</Zahtev_za_priznanje_patenta>
